# Generated by Django 2.2.7 on 2019-12-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookBook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='recipes/%Y/m/%d', verbose_name='Доп.фото'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='recipes/%Y/m/%d', verbose_name='Доп.фото'),
        ),
    ]
