# Generated by Django 2.2.7 on 2019-12-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CookBook', '0004_auto_20191212_2311'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booklikedrecipesanduser',
            unique_together={('recipe', 'user')},
        ),
    ]
